### ISSUE TITLE
[invoice-ninja]: Losing files after upgrade

### ISSUE THREAD

**Issue by jjmmbb** [getumbrel/umbrel-apps#2794]
After deploying an update to the application, all previously uploaded logo files and attached documents (e.g., PDFs, images, or other supported file types) are no longer accessible or have been permanently deleted.

**Comment by al-lac** [comment]
Hey! Did you check the invoice-ninja data folder if any files are still there? Tested the update and for me everything was still there afterwards.

**Comment by al-lac** [comment]
@jjmmbb please try to update to the latest version (5.11.78). This version should fix the issue and get your files back.

PR: https://github.com/getumbrel/umbrel-apps/pull/2809

**Comment by jjmmbb** [comment]
> [@jjmmbb](https://github.com/jjmmbb) please try to update to the latest version (5.11.78). This version should fix the issue and get your files back.
> 
> PR: [#2809](https://github.com/getumbrel/umbrel-apps/pull/2809)

Files and logos still not available after update...

![Image](https://github.com/user-attachments/assets/90164d79-c0ef-40c7-b63b-ae2fe2f0dfd6)

**Comment by jjmmbb** [comment]
Well, from what I see, the path /storage/HASH/HASH.ext is not accessible.
I have verified that and /storage/ is returning a 404 error. I can list some files in the data/storage folder of the "apps invoice-ninja" folder...
I have no idea what is causing this, as it was working before the update.

**Comment by al-lac** [comment]
Hey @jjmmbb, we found the issue. Should be fixed once #2846 is merged.

**Comment by jjmmbb** [comment]
> Hey [@jjmmbb](https://github.com/jjmmbb), we found the issue. Should be fixed once [#2846](https://github.com/getumbrel/umbrel-apps/pull/2846) is merged.

Thank you so much. Waiting for the update.

**Comment by jjmmbb** [comment]
The problem persists even after the update. I am still getting "404 | Nothing to see here!" for any file stored on /storage/.

**Comment by al-lac** [comment]
Hey @jjmmbb, i found the cause for the issue. Invoice Ninja tries to find the Icon without the port.

So it looks for something like this:
`http://umbrel.local/storage/<company-id>/<id>.png`
But it should be this URL with the port:
`http://umbrel.local:8676/storage/<company-id>/<id>.png`

Someone already opened up a ticket here: https://github.com/invoiceninja/invoiceninja/issues/10071
However it was moved to a discussion: https://github.com/invoiceninja/invoiceninja/discussions/10072

So not a lot that we can do here I think.

**Comment by al-lac** [comment]
Hey @jjmmbb. A yeah. I just tested this as well and you are right. One volume mount for nginx was still missing here. This update should fix it: https://github.com/getumbrel/umbrel-apps/pull/2905

I also had to update the APP_URL in the docker-compose.yml to match my URL and re-upload the Logo for it to work.
